### ISSUE TITLE
New Architecture

### ISSUE THREAD

**Issue by ArthurCRodrigues** [webtech-network/autograder#23]
Since we're having a different architecture in our autograding system, this is, it is now a general autograder in which users choose which tests to implement and the weight for each test field and each test subject weight.
## Change repository name 
By these means, it is crucial to change our project's name. 
# Presets approach (tagging)
As a way to providing autograder presets to users, we may use tags for each preset like:
```yml
uses: webtech-network/autograder@simpleweb
# or
uses: webtech-network/autograder@python 
```
